import localFont from "next/font/local";
import { Providers } from "./providers";
// import "./globals.css";
import { Inter } from "next/font/google";
import "../styles/index.css";
import Header from "./component/Header/index";
import Footer from "./component/Footer/index";
import ScrollToTop from "./component/ScrollToTop/index";

const inter = Inter({ subsets: ["latin"] });

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html suppressHydrationWarning lang="en">
      <head>
        <script
          async
          src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-1332484085024349"
          crossOrigin="anonymous"
        />
      </head>
      <body className={`bg-[#FCFCFC] dark:bg-black ${inter.className}`}>
        <Header />
        <Providers>{children}</Providers>
        <Footer />
        <ScrollToTop />
      </body>
    </html>
  );
}
